raidentweaks: general changes to the cli menu script
List of things that were done:

APPLIED SC2086: https://www.shellcheck.net/wiki/SC2086

APPLIED SC2006: https://www.shellcheck.net/wiki/SC2006

APPLIED SC2164: https://www.shellcheck.net/wiki/SC2104

diff --git a/system/bin/rtksmenu b/system/bin/rtksmenu
--- a/system/bin/rtksmenu
+++ b/system/bin/rtksmenu
@@ -6,19 +6,19 @@
 ID="RTKS"
 
 # Detect root
-_name=$(basename $0)
+_name=$(basename "$0")
 ls /data >/dev/null 2>&1 || { echo "$ID needs to run as root!"; echo "type 'su' then '$_name'"; exit 1; }
 
 # Magisk Mod Directory
 [ -d "/sbin/.magisk" ] && MOUNTPATH="/sbin/.magisk/modules" || MOUNTPATH="$(find /dev -mindepth 2 -maxdepth 2 -type d -name ".magisk")/modules"
 MODDIR="$MOUNTPATH/$ID"
-[ ! -d $MODDIR ] && { echo "[!] Raiden Tweaks missing..."; exit 1; }
+[ ! -d "$MODDIR" ] && { echo "[!] Raiden Tweaks missing..."; exit 1; }
 
 # Set path to your busybox if applicable
 _bb=
 
 # Load mod-util.sh
-. $MODDIR/mod-util.sh || exit $?
+. "$MODDIR"/mod-util.sh || exit $?
 
 # Set Log Files
 mount -o remount,rw /cache 2>/dev/null
@@ -33,7 +33,7 @@ stdoutLOG=$MODDIR/logs/Menu-STDOUT.log
 oldstdoutLOG=$MODDIR/logs/Menu-STDOUT-old.log
 
 # Start Logging verbosely
-mv -f $VERLOG $oldVERLOG 2>/dev/null; mv -f $LOG $oldLOG 2>/dev/null; mv -f $stdoutLOG $oldstdoutLOG 2>/dev/null
+mv -f $VERLOG $oldVERLOG 2>/dev/null; mv -f $LOG $oldLOG 2>/dev/null; mv -f "$stdoutLOG" "$oldstdoutLOG" 2>/dev/null
 # exec 3>&1
 # exec 1>$stdoutLOG
 set -x 2>$VERLOG
@@ -78,7 +78,7 @@ sdk=$(getprop ro.build.version.sdk)
 V="4.5.5"
 DEV="raidenkk"
 CDNM="4RT3M1S-S"
-magisk=`magisk -c`
+magisk=$(magisk -c)
 [[ "$(settings get global low_power)" == "1" ]] && low_power_mode="Enabled" || low_power_mode="Disabled"
 
 Menu() {
@@ -427,7 +427,7 @@ Opcao11 () {
     am kill-all
     sleep 3
     while IFS= read -r pkg_nm; do
-        [[ ${pkg_nm} != "com.termux" ]] && [[ ${pkg_nm} != "jackpal.androidterm" ]] && [[ ${pkg_nm} != "yarolegovich.materialterminal" ]] && [[ ${pkg_nm} != "com.google.android.inputmethod.latin" ]] && [[ ${pkg_nm} != "com.termoneplus" ]] && [[ ${pkg_nm} != "com.pittvandewitt.viperfx" ]] && [[ ${pkg_nm} != "com.topjohnwu.magisk" ]] && [[ ${pkg_nm} != "ridmik.keyboard" ]] && [[ ${pkg_nm} != "com.maxmpz.equalizer" ]] && [[ ${pkg_nm} != "com.miui.screenrecorder" ]] && am force-stop ${pkg_nm}
+        [[ ${pkg_nm} != "com.termux" ]] && [[ ${pkg_nm} != "jackpal.androidterm" ]] && [[ ${pkg_nm} != "yarolegovich.materialterminal" ]] && [[ ${pkg_nm} != "com.google.android.inputmethod.latin" ]] && [[ ${pkg_nm} != "com.termoneplus" ]] && [[ ${pkg_nm} != "com.pittvandewitt.viperfx" ]] && [[ ${pkg_nm} != "com.topjohnwu.magisk" ]] && [[ ${pkg_nm} != "ridmik.keyboard" ]] && [[ ${pkg_nm} != "com.maxmpz.equalizer" ]] && [[ ${pkg_nm} != "com.miui.screenrecorder" ]] && am force-stop "${pkg_nm}"
     done <<<"$(pm list packages -e -3 | grep package | cut -f 2 -d ":")"
     echo "${G}Process finished!${N}"
     echo " "
@@ -631,7 +631,7 @@ SendLogs () {
     cp -R /storage/emulated/0/.RTKS /storage/emulated/0/raidentweaks-logs
     rm -rf /storage/emulated/0/raidentweaks-logs/.RTKS/README.md
     mv /storage/emulated/0/raidentweaks-logs/.RTKS /storage/emulated/0/raidentweaks-logs/raidentweaks-logs
-    cd /storage/emulated/0/raidentweaks-logs
+    cd /storage/emulated/0/raidentweaks-logs || exit
     tar -czvf raidentweaks-logs.tar.gz raidentweaks-logs
     rm -rf /storage/emulated/0/raidentweaks-logs/raidentweaks-logs
     sleep 2
